### PR TITLE
Added circle drawing fuctions

### PR DESCRIPTION
**Pull request by pacorreia**
Added 2 new functions for drawing circles:

- outlinedCircle
- filledCircle

Will become the only extension supporting drawing circles

### CODE REVIEW

**Comment by pacorreia** [comment]
@shaoziyang would be kind to review this PR when possible please?

**Comment by HaraldRau** [comment]
Who has to merge this PR, I only have a fork on
https://github.com/makecode-extensions/OLED12864_I2C

**Comment by pacorreia** [comment]
> Who has to merge this PR, I only have a fork on https://github.com/makecode-extensions/OLED12864_I2C

only @shaoziyang appear to me the only account with permissions to merge

**Comment by HaraldRau** [comment]
I use the OLED on the Calliope Mini 3 for a weather station. It works very well!
BME280_Calliope_3_Steckplatine

**Comment by pacorreia** [comment]
> I use the OLED on the Calliope Mini 3 for a weather station. It works very well! BME280_Calliope_3_Steckplatine

Looks cool, with this PR I'm proposing, you will be able to draw circles in fast smooth way, missing from almost every extension for SSD1306

I've pushed the same change on another extension similar to this one.

after seeing most of them, I'm tempted to create an extension that captures all the good spots of each.

**Pull request merged**
